# Generated by Django 4.2.4 on 2023-09-25 16:58

import django.core.validators
from django.db import migrations, models
import user_auth.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rootUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator])),
                ('full_name', models.CharField(max_length=125)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^[6-9]\\d{9}$')])),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=125, null=True)),
                ('state', models.CharField(blank=True, max_length=125, null=True)),
                ('country', models.CharField(blank=True, max_length=125, null=True)),
                ('pincode', models.IntegerField(validators=[user_auth.models.validate_length])),
            ],
            options={
                'db_table': 'root_users',
            },
            managers=[
                ('objects', user_auth.models.userManager()),
            ],
        ),
    ]
