# Generated by Django 4.2.4 on 2023-09-25 17:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='rootuser',
            name='role',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.role'),
            preserve_default=False,
        ),
    ]
