# Generated by Django 4.2.4 on 2023-09-26 05:12

from django.db import migrations, models
import user_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_alter_usertoken_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rootuser',
            name='full_name',
            field=models.CharField(max_length=125, validators=[user_auth.models.validate_full_name]),
        ),
    ]
