# Generated by Django 4.2.4 on 2023-09-25 20:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_alter_usertoken_table'),
        ('content', '0002_contents_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 9, 25, 20, 9, 51, 120621, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contents',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_user', to='user_auth.rootuser'),
        ),
        migrations.AddField(
            model_name='contents',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contents',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_user', to='user_auth.rootuser'),
        ),
        migrations.AlterField(
            model_name='contents',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.rootuser'),
        ),
    ]
