# Generated by Django 4.2.4 on 2023-09-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_contents_created_at_contents_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='categories',
            field=models.CharField(blank=True, choices=[('category1', 'category1'), ('category2', 'category2'), ('category3', 'category3'), ('category4', 'category4'), ('category5', 'category5')], max_length=10, null=True),
        ),
    ]
